projectRoot = "../.."

compiler = "clang++"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++20",
    "-O3",
    "-g",
    "-fsanitize=address",
    "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
    "-fsanitize=undefined",
    "-Wall"
]

[[builds]]
    name = "essentials"
    buildRule = "dynamiclib"
    outputName = "Essentials"
    srcDirs = ["lib"]
    includePaths = ["include"]

[[builds]]
    name = "essentialTests"
    buildRule = "exe"
    requires = ["essentials"]
    outputName = "Tests"
    srcDirs = ["tests"]
    includePaths = [
        "/usr/include",
        "include",
        "lib"
    ]

